{
    'name': 'Nakliye Yönetim',
    'version': '1.0',
    'summary': 'Şantiye nakliye operasyonları yönetimi',
    'category': 'Operations',
    'depends': ['base', 'mail', 'account', 'hr', 'fleet', 'maintenance'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'views/santiye_views.xml',
        'views/saha_views.xml',
        'views/partner_views.xml',
        'views/sozlesme_views.xml',
        'views/hr_employee_views.xml',
        'views/gunluk_plan_views.xml',
        'views/dokum_fisi_views.xml',
        'views/kantar_fisi_views.xml',
        'views/yakit_fisi_views.xml',
        'views/yemek_plan_views.xml',
        'views/yemek_puantaj_views.xml',
        'views/hakedis_views.xml',
        'views/hakedis_wizard_views.xml',
        'views/ayarlar_views.xml',
        'views/equipment_views.xml',
        'report/hakedis_report.xml',
        'data/cron.xml',
    ],
    'installable': True,
    'application': True,
}